### PR TITLE
Fix for issue #31

### PR DESCRIPTION
**Pull request by miano**
@jdmgoogle 

Check if Python version is less than 2.7.9. If so install requests security libraries.

More info here -> http://stackoverflow.com/a/29099439

### CODE REVIEW

**Comment by jdmgoogle** [comment]
Have you tested this to see if it works? Is there even a system with python version <2.7.9 on it we can use?

**Comment by miano** [comment]
Yes, tested this on my virtual workstation that has Python 2.7.6.

Without this fix, I get the SNIMissingWarning and InsecurePlatformWarning messages. With the fix pip installs pyOpenSSL, ndg-httpsclient and pyasn1 which resolves the warnings.

**Comment by miano** [comment]
Python dev libraries are required to compile the packages above

sudo apt-get install build-essential libssl-dev libffi-dev python-dev

**Comment by jdmgoogle** [comment]
LGTM. Do we know how this will work on a Windows computer without a compiler?

Go ahead and merge, but we will probably need to update the README as to what Windows-based users can do if they don't have a compiler for this and/or the lxml package.

**Comment by miano** [comment]
I haven't tested this out on Windows. I have a Windows laptop that I can try this on later on and I'll update the documentation accordingly.

**Pull request merged**
