### PR TITLE
Add post-election sample feeds.

### PR DESCRIPTION
**Pull request by jdmgoogle**
This addresses issue #4.

Paging @miano and @ccongchen for a review.

### CODE REVIEW

**Comment by ccongchen** [comment]
LGTM. nit: I proposed a cleaner version without trailing spaces and 'empty' lines.

**Comment by jdmgoogle** [comment]
@ccongchen Please don't push updates to this branch.

It looks like my local github reverted a bunch of changed I had committed to my local repo before I pushed them upstream, which caused the issues you saw.

In the future please simply comment on the items you'd like to see changed and then let the author of the original PR fix them (similar to the internal code review process).

Let me sort this out.

**Comment by jdmgoogle** [comment]
@ccongchen Okay, fixed. Please take another look.

**Comment by ccongchen** [comment]
LGTM!

**Pull request merged**
