### PR TITLE
Update and rename README to README.md

### PR DESCRIPTION
**Pull request by ajphukan**
Add the '.md'
and corrected the typo.

### CODE REVIEW

**Comment by jdmgoogle** [comment]
@ajphukan Thank you for catching the typo!

This is not a full markdown file at the moment, and changing it from README to README.md actually breaks much of the formatting. See the [current](https://github.com/google/election_results_xml_validator/blob/master/README) vs [proposed](https://github.com/google/election_results_xml_validator/blob/099b39c7906f630d28f3b88279ec42879a4982fd/README.md) README.

If you've got a minute to fix up the formatting of e.g., the numbered lists, then I can accept this PR.

Thanks.

**Comment by ajphukan** [comment]
Okk i will try to do it ... Thanks for the feedbacks ...

**Comment by ajphukan** [comment]
I have formated the text you can check it..

**Comment by ajphukan** [comment]
I thought you forgot about the PR ... :P

**Pull request merged**
